#https://docs.docker.com/compose/gettingstarted/
version: '3'
services: 
    web:
        #https://hub.docker.com/_/nginx/
        image: nginx:stable
        restart: always
        ports:
            - "8080:80"
        volumes:
            - wordpress:/var/www/html
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
        depends_on: 
            - wordpress

    wordpress:
        #https://hub.docker.com/_/wordpress/
        image: wordpress:5.7.2-fpm
        volumes:
            - wordpress:/var/www/html
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=wordpress_user
            - WORDPRESS_DB_PASSWORD=test
            - WORDPRESS_DB_NAME=wordpress
        depends_on: 
            - db

    db:
        #https://hub.docker.com/_/mysql/
        image: mysql:latest
        volumes: 
            - database:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: hesloroota
        command: '--default-authentication-plugin=mysql_native_password'

#https://docs.docker.com/engine/reference/commandline/volume/
#docker volume ls
#docker volume inspect
#docker volume create
#docker volume rm    
volumes:
    wordpress:
    database:
    
