#https://docs.docker.com/compose/gettingstarted/
version: '3'
services:
    #Vytvoření kontejneru pro nginx 
    web:
        #Používá aktualní oficiální image nginx
        #https://hub.docker.com/_/nginx/
        image: nginx:stable
        #Restartovat pokaždé, když kontejner spadne
        restart: always
        ports:
            #Namapovat port 80 uvnitř kontejneru na vnější port 8080
            - "8080:80"
        volumes:
            #Využití volumes, pro uložení dat webové stránky
            - wordpress:/var/www/html
            #Mapování vnějšího souboru ./conf/nginx.conf na soubor v kontejneru /etc/nginx/conf.d/default.conf
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
            #Mapování vnější složky ./logs/nginx na složku v kontejneru /var/log/nginx
            - ./logs/nginx:/var/log/nginx
        #Kontejner závisí na jiných kontejnerech
        depends_on:
            # Wordpress kontejner se stará i o php 
            - wordpress

    wordpress:
        #Používá oficiální image wordpressu s php-fpm
        #https://hub.docker.com/_/wordpress/
        image: wordpress:5.7.2-fpm
        volumes:
            #Využití volumes, pro uložení dat webové stránky
            - wordpress:/var/www/html
        environment:
            #Konfigurace proměnných, které jsou nutné pro připojení wordpressu k databázi
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=wordpress_user
            - WORDPRESS_DB_PASSWORD=test
            - WORDPRESS_DB_NAME=wordpress
        #Kontejner závisí na jiných kontejnerech
        depends_on: 
            # Wordpress kontejner závisí na db kontejneru
            - db

    db:
        #Používá aktualní oficiální image mysql
        #https://hub.docker.com/_/mysql/
        image: mysql:latest
        volumes: 
            # Využití volumes pro uložení dat databáze
            - database:/var/lib/mysql
        #Restartovat pokaždé, když kontejner spadne
        restart: always
        environment: 
            #Konfigurace proměnných pro nastavení přihlašovacích údajů a názvu databáze
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: hesloroota
        command: '--default-authentication-plugin=mysql_native_password'

#Využití docker volumes, pro uchování perzistentních dat
#https://docs.docker.com/engine/reference/commandline/volume/
volumes:
    wordpress:
    database:
    
